# Note: if you modify this file, don't forget to update
# checksum in .drone.sec with:
# drone secure --repo google/material-design-lite --checksum
clone:
  depth: 1
cache:
  mount:
    - node_modules
build:
  image: crhym3/ci-image
  environment:
    - CHROME=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - WEBDRIVER=http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip
    - DISPLAY=:99
  commands:
    - npm install
    # build and unit test
    - gulp all
    - gulp mocha:closure
    # additional browser tests
    # do this after the build and unit tests to fail fast
    - Xvfb $DISPLAY &
    - curl -sSLo chrome.deb $CHROME && dpkg -i chrome.deb
    - curl -sSLo driver.zip $WEBDRIVER && unzip -q driver.zip -d /usr/bin
    # assume ok
    #- node test/memory/test.js
deploy:
  gcs_site_staging:
    image: crhym3/drone-plugin-gcs
    when:
      repo: google/material-design-lite
      branch: drone
    auth_key: >
      $$SERVICE_ACCOUNT_KEY
    source: dist
    target: mdl-test-alex
    cache_control: public,max-age=0
    acl:
      - allUsers:READER
    gzip:
      - html
      - css
      - js
      - svg
#    script:
#      - apt-get install -y python-openssl # gcloud deps for service accounts
#      - openssl aes-256-cbc -d -in .drone.p12.enc -out .drone.p12 -pass env:DRONE_PASS
#      - /gcloud/bin/gcloud components update -q gsutil
#      - /gcloud/bin/gcloud auth activate-service-account $$DRONE_ACCOUNT --key-file .drone.p12
#      - gulp publish:staging
